// src/app/layout.tsx

import type { Metadata } from 'next';
import './globals.css'


export const metadata: Metadata = {
  title: 'Lebo',
  description: 'Generated by lebo acounting',
  
}

export default function RootLayout({
  children
}:{
  children: React.ReactNode
}){
  return (
    <html lang="es" className="h-full">
       <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="h-full bg-[#0C1A1A] text-[#6ACFC7] overflow-hidden">
       
          {children}
       
      </body>
    </html>
  )
}
