// src/app/layout.tsx

import type { Metadata } from 'next';
import './globals.css'

export const metadata: Metadata = {
  title: 'Lebo',
  description: 'Generated by lebo acounting'
}

export default function RootLayout({
  children
}:{
  children: React.ReactNode
}){
  return (
    <html lang="es" className="h-full">
      <body className="h-full bg-[#0C1A1A] text-[#6ACFC7]">
        <main className="min-h-full flex flex-col items-center justify-center p-4">
          {children}
        </main>
      </body>
    </html>
  )
}
